"use client";
import { Ask } from "../lib/types";

import { useState } from "react";
import { Artifact, Career, HrSummary, Options, Recommendation, View } from "../lib/types";
import { QuestIcon as Icon } from "./QuestIcon";

const fmt: Record<string, string> = { self_paced: "В своём темпе", online: "Онлайн", offline: "Очно", hybrid: "Гибрид", workshop: "Практикум", webinar: "Вебинар" };
export const duration = (hours: number) => hours < 1 ? `${Math.round(hours * 60)} мин` : `${hours} ч`;
const scoreNames: Record<string, string> = { goal_priority: "Приоритет для цели", gap_reduction: "Сокращение разрыва", history_fit: "История участия", realism: "Доступность и нагрузка", time_efficiency: "Польза за время" };
const scoreMax: Record<string, number> = { goal_priority: 30, gap_reduction: 25, history_fit: 20, realism: 15, time_efficiency: 10 };

export function LevelCard({ career }: { career: Career }) {
  const p = career.progress;
  const percentage = p.total_required ? Math.round(p.confirmed_ready / p.total_required * 100) : 0;
  return <section className="level-card" aria-label="Текущий уровень и цель">
    <div className="level-points"><div><span className="muted tiny">СЕЙЧАС</span><strong>{career.employee.grade}</strong><span className="muted">{career.employee.role}</span></div><div className="level-link"><span/><Icon name="arrow"/><span/></div><div><span className="muted tiny">{career.target.source === "career_goal" ? "МОЯ ЦЕЛЬ" : "ТЕКУЩИЕ ТРЕБОВАНИЯ"}</span><strong>{career.target.grade}</strong><span className="muted">{career.target.role}</span></div><span className="goal-medal"><Icon name="gem" size={32}/></span></div>
    <div className="progress-label"><span>{p.total_required ? <><b>{p.confirmed_ready}</b> из {p.total_required} требований выполнены</> : "Нет требований для расчёта"}</span><b>{p.total_required ? `${percentage}%` : "—"}</b></div>
    <div className="progress-track" role="progressbar" aria-label="Подтверждённая готовность по требованиям" aria-valuenow={percentage} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${percentage}%` }}/></div>
    <div className="level-foot"><span>Оценка навыков: {career.employee.last_review_date || "нет даты"}</span><span>{p.expected_ready > p.confirmed_ready ? `После обучения ожидается: ${p.expected_ready} из ${p.total_required}` : "Повышение подтверждается отдельно"}</span></div>
    {p.unknown_required > 0 && <p className="inline-note">Нет оценки для {p.unknown_required} требований. Они не считаются освоенными.</p>}
    {career.target.source !== "career_goal" && <p className="inline-note">Карьерная цель не выбрана. Пока развиваем навыки текущей роли.</p>}
  </section>;
}

export function QuestCard({ item, career, complete, busy, ask, primary = true }: { item: Recommendation; career: Career; complete: (r: Recommendation) => void; busy: boolean; ask: Ask; primary?: boolean }) {
  return <article className={`quest-card ${primary ? "featured" : ""}`}>
    <div className="quest-top"><span className="eyebrow">{primary ? "ТВОЙ СЛЕДУЮЩИЙ КВЕСТ" : "АЛЬТЕРНАТИВНЫЙ ПУТЬ"}</span><span className="quest-score" title="Оценка соответствия, не вероятность повышения">{item.score}<small>/100</small></span></div>
    <h3>{item.title}</h3><p className="muted quest-description">{item.description}</p>
    <div className="quest-meta"><span><Icon name="clock" size={14}/>{duration(item.duration_hours)}</span><span>{fmt[item.format] || item.format}</span>{item.next_session && <span>{item.next_session}</span>}</div>
    <div className="gains">{item.covered_skills.map(s => { const gap = career.gaps.find(g => g.skill_id === s.skill_id); return <div key={s.skill_id}><span>{s.name}</span><b>{gap?.expected_level} <span className="muted">→</span> {Math.round(((gap?.expected_level || 0) + s.gain) * 10) / 10}<small> / {gap?.required_level}</small></b></div>; })}<small>Ожидаемое сокращение разрыва по требованиям</small></div>
    <details className="why"><summary>Почему этот шаг подходит мне <Icon name="spark" size={14}/></summary><ul>{item.factors.map((f,i) => <li key={i}>{f}</li>)}</ul><div className="score-detail">{Object.entries(item.components).map(([key,value]) => <div key={key}><span>{scoreNames[key]}</span><b>{value}/{scoreMax[key]}</b></div>)}</div></details>
    <div className="quest-actions"><button className="button primary" disabled={busy} onClick={() => ask(`Почему ${item.title}?`, false, {kind:"explain", event_ids:[item.event_id]})}>Разобрать с агентом <Icon name="arrow" size={16}/></button><button className="button quiet" disabled={busy} onClick={() => complete(item)}>Отметить выполненным</button></div>
  </article>;
}

function EmptyOptions({ options }: { options: Options | null | undefined }) {
  return <div className="empty-panel"><span className="empty-icon"><Icon name="compass" size={30}/></span><h3>Нужен другой путь</h3><p>Сейчас нет подходящей активности{options?.max_minutes ? ` длительностью до ${options.max_minutes} минут` : ""}.</p>{options?.exclusions.map(r => <p className="muted" key={r.reason}>{r.reason} · {r.events}</p>)}<p className="muted">Попробуйте изменить время или формат в чате. Мы не будем придумывать курсы, которых нет в каталоге.</p></div>;
}

export function EmployeeView({ career, view, artifact, busy, ask, complete }: { career: Career; view: View; artifact: Artifact | null; busy: boolean; ask: Ask; complete: (r: Recommendation) => void }) {
  const [filter, setFilter] = useState("all");
  const options = artifact?.options;
  const recs = options ? options.recommendations : career.recommendations;
  const predicted = new Map(artifact?.simulation?.flatMap(step=>step.changes.map(change=>[change.skill_id,change.after] as const))||[]);
  const gaps = career.gaps.map(g=>{const expected=predicted.get(g.skill_id)??g.expected_level;return {...g,expected_level:expected,expected_gap:expected===null?null:Math.max(0,g.required_level-expected)};}).filter(g => g.expected_gap === null || g.expected_gap > 0);
  const completed = career.achievements.quests_completed;
  if (view === "clarification") return null;
  if ((view === "explanation" || view === "comparison") && artifact?.comparison) return <div className="comparison-grid">{artifact.comparison.map(item => item.eligible ? <QuestCard key={item.event_id} item={item as Recommendation} career={career} complete={complete} ask={ask} busy={busy}/> : <article className="empty-panel" key={item.event_id}><h3>{item.title}</h3><p>{item.explanation}</p><span>Сейчас недоступно</span></article>)}</div>;
  if (view === "history") return <section className="history-list"><div className="section-heading"><h2>Твои пройденные этапы</h2><span className="badge">Последние 30</span></div>{career.history.length ? career.history.map(h => <article key={h.record_id}><span className={`history-icon ${h.status === "completed" ? "done" : ""}`}><Icon name={h.status === "completed" ? "check" : "clock"}/></span><div><h3>{h.title}</h3><p className="muted">{h.date} · {({ completed: "Выполнено", in_progress: "В процессе", skipped: "Пропущено", declined: "Отклонено", registered: "Запланировано", no_show: "Не посещено" } as Record<string,string>)[h.status] || h.status}</p></div><b>{h.completion_pct}%</b></article>) : <div className="empty-panel">Истории участия пока нет.</div>}</section>;
  if (view === "skill_guide" && artifact?.guide) return <><LevelCard career={career}/><article className="guide-panel"><span className="eyebrow">ИЗ СПРАВОЧНИКА НАВЫКОВ</span><h2>{artifact.guide.skill.name}</h2><p>{artifact.guide.skill.description}</p><div className="exercise"><span className="badge"><Icon name="leaf" size={14}/> Учебный пример</span><h3>Попробуй на практике</h3><p>{artifact.guide.example}</p><small>{artifact.guide.label}</small></div></article></>;
  return <>
    <LevelCard career={career}/>
    {view === "skill_map" || view === "level" ? <section className="skill-section"><div className="section-heading"><div><span className="eyebrow">ТВОИ СУПЕРСИЛЫ И ТОЧКИ РОСТА</span><h2>Карта навыков</h2></div><div className="filter-buttons" aria-label="Тип навыков">{[["all","Все"],["hard","Hard"],["soft","Soft"]].map(([id,label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div></div><div className="skill-legend"><span><i/>Подтверждено</span><span><i className="expected"/>Ожидается</span><span>Шкала 0–5 · цель указана справа</span></div><div className="skill-grid">{career.gaps.filter(g => filter === "all" || g.type === filter).map(g => <article key={g.skill_id} className={`skill-card ${g.expected_gap === 0 ? "achieved" : ""}`}><div className="skill-card-top"><span className="skill-symbol"><Icon name={g.gap === 0 ? "check" : g.critical ? "gem" : "skills"}/></span><span className={`skill-status ${g.gap === 0 ? "done" : ""}`}>{g.current_level === null ? "Нужна оценка" : g.gap === 0 ? "Освоено" : g.critical ? "Ключевой для цели" : "Точка роста"}</span></div><h3>{g.name}</h3><p className="muted">{g.category}</p><div className="skill-scale" aria-label={`Подтверждено ${g.current_level}, ожидается ${g.expected_level}, требуется ${g.required_level}`}>{[0,1,2,3,4].map(n => <span key={n}><i style={{width:`${Math.max(0,Math.min(1,(g.current_level??0)-n))*100}%`}}/><em style={{width:`${Math.max(0,Math.min(1,(g.expected_level??0)-n))*100}%`}}/></span>)}</div><div className="skill-values"><b>{g.current_level??"Нет оценки"}<span className="muted"> / 5</span></b><span>Цель: {g.required_level}</span></div>{g.expected_level !== null && g.current_level !== null && g.expected_level > g.current_level && <p className="projected-note">Ожидается после обучения: {g.expected_level}</p>}<button className="text-button" disabled={busy} onClick={() => ask(`Объясни ${g.name} на примере`)}>Как развивать <Icon name="arrow" size={14}/></button></article>)}</div>{career.current_skills?.filter(s => !career.gaps.some(g => g.skill_id === s.skill_id) && (filter === "all" || s.type === filter)).map(s => <article className="skill-card" key={s.skill_id}><h3>{s.name}</h3><p>Подтверждено: {s.current_level}/5 · ожидается: {s.expected_level}/5</p><small>Не входит в требования выбранной цели</small></article>)}{!career.gaps.length && <div className="empty-panel">Для этой роли пока нет требований в наборе.</div>}</section> : <>
    {completed > 0 && <div className="achievement" role="status"><span className="achievement-medal"><Icon name="award" size={25}/></span><div><strong>{completed === 1 ? "Первый шаг сделан" : "Путь продолжается"}</strong><span>{completed} квестов выполнено · каждый шаг имеет значение</span></div><Icon name="spark"/></div>}
    <div className="section-heading"><div><span className="eyebrow">НЕБОЛЬШИЕ ШАГИ. ЗАМЕТНЫЙ ПРОГРЕСС.</span><h2>{view === "next_step" ? "Выбери следующий квест" : "Твой маршрут развития"}</h2></div><span className="badge"><Icon name="flag" size={13}/> Личный путь</span></div>
    {view === "next_step" ? <div className="recommendation-list">{recs.length ? recs.map((r,i) => <QuestCard key={r.event_id} item={r} career={career} complete={complete} ask={ask} busy={busy} primary={i===0}/>) : <EmptyOptions options={options}/>}</div> : <div className="journey">
      <div className="journey-stop"><div className="journey-node done"><Icon name="check" size={22}/></div><div className="stop-copy"><span className="eyebrow">ТОЧКА СТАРТА</span><h3>{career.employee.grade} · основа уже с тобой</h3><p>{career.progress.confirmed_ready} требований подтверждено. Остальное пройдём шаг за шагом.</p></div></div>
      <div className="journey-stop active"><div className="journey-node active"><Icon name="compass" size={25}/></div><div>{recs.length ? <QuestCard item={recs[0]} career={career} complete={complete} ask={ask} busy={busy}/> : <EmptyOptions options={options}/>}</div></div>
      <div className="journey-stop"><div className="journey-node"><Icon name="flag" size={22}/></div><div className="stop-copy"><span className="eyebrow">{artifact?.simulation?.length?"ПОСЛЕ ШАГА · ПРОГНОЗ":"СЛЕДУЮЩИЕ ВЕРШИНЫ"}</span><h3>{gaps.length ? "Закрыть оставшиеся требования" : "Подтвердить результат"}</h3><div className="remaining-skills">{gaps.slice(0,4).map(g => <span key={g.skill_id}>{g.name} <b>{g.expected_level??"Нет оценки"}/{g.required_level}</b></span>)}{gaps.length>4 && <span>Ещё {gaps.length-4} на карте навыков</span>}</div><p>Следующий шаг будет проверен заново. Предварительные навыки требуют подтверждённой оценки; прогноз обучения не открывает доступ автоматически.</p></div></div>
      <div className="journey-stop finish"><div className="journey-node"><Icon name="gem" size={24}/></div><div className="stop-copy"><span className="eyebrow">{career.target.source==="career_goal"?"ТВОЯ ЦЕЛЬ":"ТРЕБОВАНИЯ ТЕКУЩЕЙ РОЛИ"}</span><h3>{career.target.grade} · {career.target.role}</h3><p>Готовность по навыкам и обсуждение грейда с руководителем.</p></div></div>
    </div>}
    </>}
  </>;
}

export function TeamView({ data, view, ask, busy }: { data: HrSummary; view: View; ask: Ask; busy: boolean }) {
  const max = Math.max(1,...data.top_gaps.map(g => g.employees));
  return <><div className="team-metrics"><div><span>В разрешённом отделе</span><strong>{data.employee_count}</strong><small>сотрудников</small></div><div><span>Нужен следующий шаг</span><strong>{data.employees_without_recommendations.length}</strong><small>сотрудников с дефицитами</small></div><div><span>Завершено участий</span><strong>{data.participation.completion_rate}<small>%</small></strong><small>{data.participation.completed} из {data.participation.total_records}</small></div></div>
  {view === "hr_events" ? <section className="team-panel"><h2>Участие по активностям</h2><p className="muted">Количество записей участия, включая повторные события.</p><div className="event-table"><div className="event-table-head"><span>Активность</span><span>Участий</span><span>Завершено</span></div>{data.events.map(e => <div key={e.event_id}><span>{e.title}</span><b>{e.participants}</b><b>{e.completed}</b></div>)}</div></section> : view === "hr_coverage" ? <section><div className="section-heading"><h2>Кому нужен маршрут</h2><span className="badge">{data.department}</span></div><div className="coverage-list">{data.employees_without_recommendations.map(p => <article key={p.employee_id}><div className="person-row"><span className="mini-avatar">{p.full_name.split(" ").map(w=>w[0]).slice(0,2).join("")}</span><div><h3>{p.full_name}</h3><span className="muted">{p.target_role} · {p.employee_id}</span></div></div><ul>{p.reasons.map(r => <li key={r.reason}>{r.reason} <span className="muted">({r.events})</span></li>)}</ul></article>)}{!data.employees_without_recommendations.length && <div className="empty-panel"><Icon name="check"/><h3>Следующий шаг есть у всех</h3><p>Среди сотрудников с незакрытыми требованиями.</p></div>}</div></section> : <><section className="team-panel"><div className="section-heading"><div><span className="eyebrow">ГДЕ НУЖНА ПОДДЕРЖКА</span><h2>Самые частые дефициты</h2></div><Icon name="chart"/></div><div className="team-bars">{data.top_gaps.map((g,i)=><div key={g.name}><div><span><small>{String(i+1).padStart(2,"0")}</small>{g.name}</span><b>{g.employees}<small> чел.</small></b></div><div className="progress-track"><span style={{width:`${g.employees/max*100}%`}}/></div></div>)}</div><p className="muted tiny">Потребности в развитии относительно целей. Не рейтинг результативности людей.</p></section><section className="team-callout"><span className="callout-icon"><Icon name="compass" size={28}/></span><div><h3>Обучение есть. Следующий шаг — не у всех.</h3><p className="muted">Разберём причины и найдём пробелы в программе развития.</p><button className="text-button" disabled={busy} onClick={()=>ask("У кого в команде нет следующего шага?")}>Разобрать с агентом <Icon name="arrow" size={16}/></button></div></section></>}
  </>;
}
